repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.4'
    hooks:
    -   id: clang-format
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.1.6
  hooks:
    # Run the linter.
    - id: ruff
    # Run the formatter.
    - id: ruff-format
